### ISSUE TITLE
Numeric keyboard on iOS and Android

### ISSUE THREAD

**Issue by blaforet** [nbfontana/ngx-currency#1]
Hi
With the use of ngx-currency in an input field, how can i force the use of numeric keyboard on iOS and Android devices?

Thank you

**Comment by nbfontana** [comment]
Hi @blaforet,

Are you using Ionic 3? So I can reproduce the behavior

**Comment by blaforet** [comment]
Hi
I'm not using ionic ( for the moment).
For now it's a simple web app.

Thank you

**Comment by nbfontana** [comment]
### Hello @blaforet, 

"ngx-currency" is only responsible for the content transformation, it gets the keyboard input and transforms it based on the [options].

#### Input
```
<label>Example</label>
<input class="form-control"
  maxlength="20"
  currencyMask formControlName="value"
  [(ngModel)]="value"
  [placeholder]="'R$ 0,00'"
  [options]="ngxCurrencyOptions"/>
```

#### Config
```
public ngxCurrencyOptions = {
    prefix: 'R$ ',
    thousands: '.',
    decimal: ',',
    allowNegative: false
  };
```

That said, the *<input>* tag is responsible for triggering the keyboard in mobile, and you can achieve that behavior in different ways.

Googling around I found this post: 
http://blog.pamelafox.org/2012/05/triggering-numeric-keyboards-with-html5.html

It has a lot of explanation about the subject an
e"
  [placeholder]="'R$ 0,00'"
  [options]="ngxCurrencyOptions"/>
```

#### Config
```
public ngxCurrencyOptions = {
    prefix: 'R$ ',
    thousands: '.',
    decimal: ',',
    allowNegative: false
  };
```

That said, the *<input>* tag is responsible for triggering the keyboard in mobile, and you can achieve that behavior in different ways.

Googling around I found this post: 
http://blog.pamelafox.org/2012/05/triggering-numeric-keyboards-with-html5.html

It has a lot of explanation about the subject and also points some solutions for different browser =D

Hope it can help you!

**Comment by blaforet** [comment]
Hi 
Now it's working. 
Yes, I've also  found the same page has you did.  Did try everything they said without luck.
But in the comments someone mention **input type="tel"**  and it's now working on Android and iOS

Thank you
