### ISSUE TITLE
Configuration token not exported

### ISSUE THREAD

**Issue by patkec** [nbfontana/ngx-currency#116]
Hi,

I would need to globally configure the mask based on LOCALE_ID. Currently I cannot do that, because CURRENCY_MASK_CONFIG token is not exported. I would like to do something like this:
```
import { CURRENCY_MASK_CONFIG } from 'ngx-currency'; // <-- This doesn't work

@NgModule({
  ...,
  providers: [
    ...,
    { provide: CURRENCY_MASK_CONFIG, useClass: CustomCurrencyMaskConfig }
  ]
})
export class AppModule {}

@Injectable()
export class CustomCurrencyMaskConfig {
  ...
  constructor(@Inject(LOCALE_ID) locale: string) {
    this.decimal = getLocaleNumberSymbol(locale, NumberSymbol.Decimal);
  }
}
```

**Comment by nbfontana** [comment]
Hi @patkec, I believe that this is a simple feature and we can implement it. I'll take a look into it this week, but feel free to submit a PR if you want. Just let me know you are working on it before.

**Comment by patkec** [comment]
Hi @nbfontana , sorry for my late reply. I'll have a look at this today and add a PR.

**Comment by giovannipds** [comment]
Can we apply this PR?

**Comment by giovannipds** [comment]
Better late than never. 🤣 Thanks.
