### ISSUE TITLE
Unexpected behaviour pressing backspace in NATURAL mode when value is 0

### ISSUE THREAD

**Issue by MattPress** [nbfontana/ngx-currency#117]
Code example here https://angular-ngx-currency.stackblitz.io/
Steps:
1. Natural mode
2. Value of 0.00
2. Place cursor after decimal
2. Press backspace

Expected Result: cursor is moved to position prior to the decimal
Actual result: cursor doesn't move.
 
When the input has a whole number other than 0 this works as expected.

**Comment by MattPress** [comment]
Fix added in https://github.com/nbfontana/ngx-currency/pull/118

**Comment by nbfontana** [comment]
This issue has been fixed by @MattPress with #118 and its available at v2.5.2
