### ISSUE TITLE
Why do values have to start from right to left.

### ISSUE THREAD

**Issue by HelloooJoe** [nbfontana/ngx-currency#157]
Unless I didn't see in the docs how I can start from left to right, this is a pretty lame lib. 

E.g. If I start typing 99 the input shows $ 0.99. I want it to show $99 and then let me decide when to put the decimal.

**Comment by leonardomnds** [comment]
You can use this config option: `inputMode: CurrencyMaskInputMode.NATURAL`.
By dafault, this config is `CurrencyMaskInputMode.FINANCIAL`.

**Comment by samucancld** [comment]
Read the readme Joe...

**Comment by shyamal890** [comment]
@nbfontana Can we please close this issue

**Comment by HelloooJoe** [comment]
I figured it out 572 days ago... thanks for nothing

**Comment by nbfontana** [comment]
:shipit:
