### ISSUE TITLE
Error in new version 4.0.0

### ISSUE THREAD

**Issue by LuisCampos97** [nbfontana/ngx-currency#181]
@ArtemDintecom @nbfontana 
When I compile with ng serve I have this error in new version 4.0.0:

```typescript
Error: node_modules/ngx-currency/lib/ngx-currency.directive.d.ts:29:91 - error TS2344: Type '{ options: { alias: "options"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"options"' is incompatible with index signature.
    Type '{ alias: "options"; required: false; }' is not assignable to type 'string'.

29     static ɵdir: i0.ɵɵDirectiveDeclaration<NgxCurrencyDirective, "[currencyMask]", never, { "options": { "alias": "options"; "required": false; }; }, {}, never, never, true, never>;
```

**Comment by ArtemDintecom** [comment]
Unfortunately, I was unable to reproduce this error. Could you provide a code example that results in this error?
Based on the error message, I would assume that you have made an extra wrapper in the form of an options object. Something like that:
```html
<input currencyMask [options]="ngxCurrencyOptions" />
```
```ts
ngxCurrencyOptions = {
  options: {
    prefix: '$ ',
    thousands: '.',
  },
};
```
But it should be like this:
```ts
ngxCurrencyOptions = {
  prefix: '$ ',
  thousands: '.',
};
```

**Comment by ArtemDintecom** [comment]
It's probably worth mentioning this in the README, because only Angular 16 is already listed in peerDependencies:
https://github.com/nbfontana/ngx-currency/blob/1b561bcd004fe090e603cb601ce6cad9267f119d/projects/ngx-currency/package.json#L24-L28

**Comment by nbfontana** [comment]
:shipit:
