### ISSUE TITLE
[ERROR] NG8002: Can't bind to 'currencyMask' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by Ben555555** [nbfontana/ngx-currency#199]
I'm trying to use it with options but getting the following error with Angular 17 and 18:

_X [ERROR] NG8002: Can't bind to 'currencyMask' since it isn't a known property of 'input'. [plugin angular-compiler]

    src/app/portal/....html:59:62:
      59 │ ...hildRate" [currencyMask]="{ prefix: 'R$ ', thousands: '.', deci..._
      
      
I'm using it like this as in the instructions:
      
html:
```
<mat-form-field class="w-100">
    <mat-label>Test</mat-label>
    <input matInput [formControl]="formGroup.controls.rate" [currencyMask]="{ prefix: 'R$ ', thousands: '.', decimal: ',' }">
 </mat-form-field>
```
  
ts:  
```
        @Component({
  selector: 'app-detail',
  templateUrl: './idetail.component.html',
  styleUrls: ['./detail.component.scss'],
  standalone: true,
  imports: [FormsModule, ReactiveFormsModule, MatFormFieldModule, MatInputModule,
    MatDialogTitle, MatDialogContent, MatDialogActions, MatButtonModule,
    TranslateModule, InfoIconComponent, MatSelectModule, MatDatepickerModule, MatCheckboxModule, NgxCurrencyDirective]
})
```

It only works with the global provider and the currencyMask directive without options.

**Comment by ArtemDintecom** [comment]
@Ben555555 Which version of ngx-currency are you using?
This way you can only pass parameters in 18.0.0. In version 17.0.0 and earlier you had to do this:
https://github.com/nbfontana/ngx-currency/blob/8681e4c55a645da6559142ef79fd698195253657/README.md?plain=1#L61-L65
