### ISSUE TITLE
[FEATURE] Ability to type in decimal point

### ISSUE THREAD

**Issue by arielgelbard** [nbfontana/ngx-currency#2]
I would love to have an enhancement where a decimal ('.') could be typed in instead of automatically appearing

example: [text-mask](https://text-mask.github.io/text-mask/)
In this demo, if you select "US dollar amount (allows decimal)" from the dropdown list, the decimal does not appear until a user has typed it in
 
Thank you very much for creating ngx-currency. Loving it!

**Comment by limedot** [comment]
Hello. Any news about this enhancement ?

**Comment by nbfontana** [comment]
Help wanted

**Comment by nbfontana** [comment]
Fixed after https://github.com/nbfontana/ngx-currency/pull/80
