### ISSUE TITLE
Not working with ngModel

### ISSUE THREAD

**Issue by danillo10** [nbfontana/ngx-currency#24]
Not working!
<input [(ngModel)]="valor_frete" currencyMask [options]="{ prefix: '', thousands: '.', decimal: ',' }" class="input-default validateFormat validadeNumber calculaTotal" id="frete_pedido" name="frete_pedido" type="text">

Working 
<input currencyMask [options]="{ prefix: '', thousands: '.', decimal: ',' }" class="input-default validateFormat validadeNumber calculaTotal" id="frete_pedido" name="frete_pedido" type="text">

**Comment by nbfontana** [comment]
There's not enough context to work in this Issue.
Local tests seem to be working just fine.
