### ISSUE TITLE
TypeError: Cannot set property 'align' of undefined

### ISSUE THREAD

**Issue by diegotakeo** [nbfontana/ngx-currency#25]
Hello,
Currently I am having the following error "TypeError: Cannot set property 'align' of undefined" as I run karma test with any components that make use of the CurrencyMaskModule.

I am using Angular 6 and the v1.5.0 of ngx-currency.
I had the exact same issue with v5.3.1 of ng2-currency-mask.

The error disappears as I comment line 33 of the currency-mask.directive.js
this.elementRef.nativeElement.style.textAlign = this.options.align ? this.options.align : this.optionsTemplate.align;

This issue only appears with ng test but nothing wrong with the ng serve.
Any ideas?

**Comment by diegotakeo** [comment]
This could literally be solved by simply changing this (line 33 of currency-mask.directive.js):

    this.elementRef.nativeElement.style.textAlign = this.options.align ? this.options.align : this.optionsTemplate.align;

To this:

    this.elementRef.nativeElement.style.textAlign = this.options ? this.options.align : this.optionsTemplate.align;

I would appreciate the heck out of you if you did this little change in the next update.

Cheers!

**Comment by nbfontana** [comment]
Hi @diegotakeo,

Feel free to make a Pull Request with those fix.
 I'll be happy to release a version as soon as I can.

**Comment by diegotakeo** [comment]
@nbfontana  Awesome! Pull request created. 
Thanks for your attention :)

**Comment by diegotakeo** [comment]
@nbfontana

**Comment by nbfontana** [comment]
I've just approved your PR. I'll publish a version today.

**Comment by diegotakeo** [comment]
Thanks a lot :)

**Comment by nbfontana** [comment]
Fixed in **v1.5.1**

Check: https://www.npmjs.com/package/ngx-currency

Thanks @diegotakeo!
If something's wrong with the version, feel free to re-open the Issue.
