### ISSUE TITLE
currencyMask with readony

### ISSUE THREAD

**Issue by odione** [nbfontana/ngx-currency#28]
Hi

When I use currencyMask on a <input> with readonly property, readonly is ignored.

`<input type="tel" matInput placeholder="Subtotal" formControlName="valorTotal" currencyMask readonly="true">`

Even with readonly property set to true, I can change de control value.

**Comment by nbfontana** [comment]
I believe your problem is too old, but it may be solved using HTML5 `disabled` property.

**Comment by biltongza** [comment]
The problem with using disabled is it changes the styling which we don't want. We can work around this with CSS, but it would be nice if readonly actually worked.

**Comment by re2005** [comment]
Same problem here if directive currencyMask is applied, it will make a readOnly input editable.
