### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by ispadoto** [nbfontana/ngx-currency#29]
Hello everyone! 

I'm trying to use ngx-currency but, I' getting an error on change the value of the input

TypeError: Cannot read property 'apply' of undefined
    at CurrencyMaskDirective.handleBlur (currency-mask.directive.js:45)

I have no idea to solve that, somebody could help me? 

The snip code: 

`<ion-input currencyMask type="tel" [options]="{ suffix: 'km', thousands: '.', decimal: ',' }" name="kmMedia"  [(ngModel)]="ivecoTCO.aplicacao.kmMediaAnual"></ion-input>`

The installation I followed the documentation. 

**System data:**

Ionic:

   ionic (Ionic CLI)  : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/ibere/Library/Android/sdk)
   ios-deploy        : 1.9.1
   ios-sim           : 5.0.8
   NodeJS            : v8.11.1 (/usr/local/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by ispadoto** [comment]
Sometimes the error changes: 

ERROR TypeError: Cannot read property 'createRange' of undefined
    at InputManager.get [as inputSelection] (input.manager.js:46)
    at InputService.get [as inputSelection] (input.service.js:144)
    at InputHandler.handleInput (input.handler.js:17)
    at CurrencyMaskDirective.handleInput (currency-mask.directive.js:54)

**Comment by ispadoto** [comment]
I found the origin of problem... Is the ion-input, the component only works with <input> tag...

**Comment by jackrvaughan** [comment]
Hi @ispadoto - what do you mean by only works with tag?

**Comment by nbfontana** [comment]
@jackrvaughan it means he's trying to use the component in another component, which is the `<ion-input>`, but the directive only works if you apply it directly to an HTML5 `<input />`.

It doesn't support Ionic at this level, yet.
