### ISSUE TITLE
Clicking input before the placeholder text issue

### ISSUE THREAD

**Issue by arielgelbard** [nbfontana/ngx-currency#3]
If the placeholder text is aligned left, and the user clicks the input where the placeholder text begins, the cursor will appear before the placeholder text and append the placeholder text when typing

Example: 
placeholder='0.00'
Result from clicking at beginning of placeholder text: 30.00

Expected Result: 0.03

**Comment by ayoolakelani** [comment]
Hi nbfontana, i will try to help fix this issue. i am a first timer  and trying to contribute to open source.

Thanks

**Comment by nbfontana** [comment]
Hi @ayoolakelani,

Thank you! I'll look into it later.

**Comment by nbfontana** [comment]
I'll move this Issue to check the actual need of it.
