### ISSUE TITLE
More than one custom value accessor matches form control with unspecified name attribute when using with Ionic 4

### ISSUE THREAD

**Issue by rondog** [nbfontana/ngx-currency#30]
When I try and use this with an `<ion-input currencyMask></ion-input>` an error is presented that says:

> More than one custom value accessor matches form control with unspecified name attribute

It works fine when I use it with a standard `<input>` tag, but then I lose all of the ionic features of an ion-input. Any ideas how to fix this?

**Comment by odione** [comment]
I have same problem with Ionic 4

**Comment by nbfontana** [comment]
ngx-currency doesn't support Ionic since it can't find the input tag, it must have an HTML5 input tag as base.

**Comment by Slavrix** [comment]
To make it look like its working with ionic 4

you can place an input inside and ion-input

them apply this css to the internal input;
.fakeInput {
  width: 100%;
  border: none !important;
  outline: none !important;
}
its hacky, but it does the job.

**Comment by ViteRoberto** [comment]
> To make it look like its working with ionic 4
> 
> you can place an input inside and ion-input
> 
> them apply this css to the internal input;
> .fakeInput {
> width: 100%;
> border: none !important;
> outline: none !important;
> }
> its hacky, but it does the job.

:D! It was exactly what i was looking for!!

**Comment by dmastag** [comment]
I don't understand how this works
Would anyone be able to submit an example ?

**Comment by danielehrhardt** [comment]
> width: 100%;
> border: none !important;
> outline: none !important;

```
<ion-input type="tel" name="monthlyBill" currencyMask>
        <input currencyMask formControlName="value" />
      </ion-input>
```
