### ISSUE TITLE
Null thousands separator not handled correctly

### ISSUE THREAD

**Issue by jOWNziE** [nbfontana/ngx-currency#31]
We'd like to be able to set the thousands separator to null in order to get the "numeric-only" benefit of the mask, without having to have spaces in between the digits. 

We'd really like to use this mask though, as opposed to a simple number mask, because we have dynamically created "number" input controls which are then defined either to have a thousands separator or not, but they all need to use the same mask.

Currently, setting thousands to null results in the string "null" being used as the separator.

**Comment by nbfontana** [comment]
### Update

The PR has been merged.
This feature is available in **v1.5.2.**

:rocket:
