### ISSUE TITLE
How does this project differ from ng2-currency-mask?

### ISSUE THREAD

**Issue by JWess** [nbfontana/ngx-currency#34]
How does this project differ from https://github.com/cesarrew/ng2-currency-mask?

**Comment by nbfontana** [comment]
Hello @JWess,

It has some **bug fixes**.

I tried ng2-currency-mask in a project and it seemed to **not work with Firefox** and had a feel weird behaviors.

I decided to make some changes and those were never accepted in the other project. Then, I decided to make a new one.
