### ISSUE TITLE
Mobile Phone problem

### ISSUE THREAD

**Issue by lorranpalmeira** [nbfontana/ngx-currency#37]
I had a problem with ngx-currency in mobile phone, because when you delete all text field you dont get fill correctly.

**Comment by lorranpalmeira** [comment]
Change to nullable: false.

export const customCurrencyMaskConfig = {
  align: "right",
  allowNegative: true,
  allowZero: true,
  decimal: ",",
  precision: 2,
  prefix: "R$ ",
  suffix: "",
  thousands: ".",
  nullable: false
};

**Comment by nbfontana** [comment]
Solved
