### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by joaogoya** [nbfontana/ngx-currency#39]
I follow the steps, and get this error:
Can't bind to 'options' since it isn't a known property of 'input

Angular CLI: 7.3.3
Node: 10.15.3
OS: win32 x64
Angular: 7.2.7
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/animations               7.2.11
@angular/cli                      7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

**Comment by nbfontana** [comment]
Hi @joaogoya,

It looks like you're using Angular 7 and we still using Angular 4 in this project. 

I'll create a separated Issue to migrate the project and open it to the community.

**Comment by nbfontana** [comment]
It will be fixed in this other Issue: #40 

I'll be closing this one for now.
