### ISSUE TITLE
Reactive Form

### ISSUE THREAD

**Issue by caglarturkurka** [nbfontana/ngx-currency#4]
hi, I want to use your ngx-currency in my project, but it does not work for Reactive Form.Could you explain it how can I use ngx-currency in Reactive Form for input tag

**Comment by nbfontana** [comment]
Hi @caglarturkurka, sorry for the late answer... I've been away from Angular for a while.

I don't know if the doubt is still valid, but, ngx-currency can be used with Reactive Forms. You can see an example [here](https://github.com/nbfontana/ngx-br/tree/master/src/app/components/dinheiro), it's an "money" component that encapsulates ngx-currency in another component.

I believe that it's a good approach.

**Comment by adjeteyadjei** [comment]
Hi @nbfontana,
The example at [https://github.com/nbfontana/ngx-br/tree/master/src/app/components/dinheiro](url) is **not** using reactive form. Its uses template-driven form.
