### ISSUE TITLE
Make it work with Angular 7+

### ISSUE THREAD

**Issue by nbfontana** [nbfontana/ngx-currency#40]
When using **ngx-currency** with Angular 7 we get the folowing error: **Can't bind to 'options' since it isn't a known property of 'input**

We need to upgrade it to work with newer versions.

It should work in a environment like this:

```
Angular CLI: 7.3.3
Node: 10.15.3
OS: win32 x64
Angular: 7.2.7
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

**Comment by duffbuster** [comment]
@nbfontana ok if I take a stab at this? I need this for an Angular 7 project.

**Comment by nbfontana** [comment]
Sure! Go for it :100:

**Comment by nbfontana** [comment]
Just saw your PR. I'll check it and generate a new version if everything's ok.

**Comment by nbfontana** [comment]
Fixed with a new version: **v2.0.0 - Angular 7 Support**

**Comment by ganholete** [comment]
keeps warning in angular 8, but it works!

**Comment by tayambamwanza** [comment]
@nbfontana I also get the warning: Can't bind to 'options' since it isn't a known property of 'input' although it is still working.
