### ISSUE TITLE
Ignore special characters when maxlength is set

### ISSUE THREAD

**Issue by lunaboona** [nbfontana/ngx-currency#43]
I'd like to add a maxlength to my inputs, but I'm having an issue where non-number characters (R$, spaces, dots and commas) count towards the total length.

**Comment by bburns-dev** [comment]
@lunaboona I have a fix for this, changing the maxLength check to use 'onlyNumbers' instead of the raw input value.

**Comment by nbfontana** [comment]
Sorry I'm late on this. Merged. I'll release a version today.

Great work @bburns-dev :tada:
