### ISSUE TITLE
Directive allows % signs 

### ISSUE THREAD

**Issue by biltongza** [nbfontana/ngx-currency#50]
See stackblitz here: https://stackblitz.com/edit/ngx-currency-percent
![image](https://user-images.githubusercontent.com/2845704/60804928-02b75a80-a17f-11e9-865d-c02c9880443a.png)
You can put any number of percent signs in the input. It doesn't appear to have any impact on the value, but it is inconsistent since the directive blocks all other non-numeric characters.

**Comment by nbfontana** [comment]
Available at version `v2.2.4`
