### ISSUE TITLE
Copy paste is not formatting the amount properly if we don't have decimals

### ISSUE THREAD

**Issue by rmganesh6** [nbfontana/ngx-currency#53]
If we copy amount 100 without decimal like 100.00 then it's pasted as 1.00. please check and fix the same.

**Comment by Prinsn** [comment]
So is this project just a forj of ng2-currency with a ll the same problems?

**Comment by nbfontana** [comment]
@Prinsn nah, the original didn't even worked on Firefox. And some issues are really resolved by open-sourcerers.

**Comment by nbfontana** [comment]
Fixed after https://github.com/nbfontana/ngx-currency/pull/80
