### ISSUE TITLE
currencyMask with readony

### ISSUE THREAD

**Issue by re2005** [nbfontana/ngx-currency#55]
First of all, Obrigado!

I would like to re-open this issue:
https://github.com/nbfontana/ngx-currency/issues/28

Can you please elaborate on how to make it work, using currencyMask together with readonly flag ?

Current the input still editable.

Thanks

**Comment by andre-f-paggi** [comment]
Even with [disabled] I coult not make it work. I will try to fork and solve this

**Comment by mustafakunwa** [comment]
Have you find any solution?

**Comment by nbfontana** [comment]
Available at version `v2.2.4`

Special thanks to @dvenkatsagar :tada:

**Comment by cstruter** [comment]
Currently using v2.5.1 and this issue still persist?
