### ISSUE TITLE
clear value

### ISSUE THREAD

**Issue by ali7091** [nbfontana/ngx-currency#6]
how can i clear value ?
when i insert value into input then i cant clear its value and value is 0
but i want to be able to clear value(null)

**Comment by nbfontana** [comment]
Hi @ali7091, sorry for the late answer.

I'll see what I can do, maybe an option that changes that behavior?

**Comment by LucasLopesr** [comment]
@nbfontana I thought the same way, I made the change on my fork. [Commit](https://github.com/LucasLopesr/ngx-currency/commit/d3f40e487fc8e63d6f393182491fc102f29e4b39)

**Comment by nbfontana** [comment]
Fixed!

I'll generate a version tonight!

Thx @LucasLopesr

**Comment by nbfontana** [comment]
Fixed in [**v1.2.0**](https://www.npmjs.com/package/ngx-currency)!
