### ISSUE TITLE
Feature request: change when mask is applied

### ISSUE THREAD

**Issue by biltongza** [nbfontana/ngx-currency#60]
We have users complaining that when they want to type in for example $100, they actually have to type in "10000" because of the decimal places.

The problem is that the input always happens from the least significant digit, in the fraction/decimal part, where our users most common use case is from the whole unit part onwards.

The suggestion is to let the user type in "100" and only apply the mask after blurring the control, instead of on every keypress.

I am happy to attempt this work myself, but I'm not quite sure where to start.

**Comment by nbfontana** [comment]
Fixed after https://github.com/nbfontana/ngx-currency/pull/80
