### ISSUE TITLE
<input readonly> property doesn't work

### ISSUE THREAD

**Issue by thaodn** [nbfontana/ngx-currency#61]
I have a input control, which uses currencyMask and readonly directive.
When I opened the form, the input was readonly grey background, but I could still enter or using keyboard on it, it's not working

<input type="text" formControlName="rateNew" id="rateNew" [(ngModel)]="model.rateNew" placeholder="..." readonly="readonly" currencyMask [options]="rateMaskOptions" />

**Comment by mustafakunwa** [comment]
Same Issue readonly Doesn't work

**Comment by nbfontana** [comment]
Available at version `v2.2.4`

Special thanks to @dvenkatsagar :tada:
