### ISSUE TITLE
Does not compile with Angular v9

### ISSUE THREAD

**Issue by exequiel09** [nbfontana/ngx-currency#63]
Running `ngcc` against an Application using Angular v9-rc.6 fails to compile. Please see the following screenshot below.

<img width="1500" alt="Screen Shot 2019-12-20 at 8 22 02 AM" src="https://user-images.githubusercontent.com/1289472/71219932-d98c2000-2301-11ea-921e-3941e7e875c4.png">

It might be related on how this component is built? Issues in Angular that might have a clue on how to fix `ngx-currency` in Angular v9:

1. https://github.com/angular/angular/issues/30972
2. https://github.com/angular/angular/issues/32442

**Comment by exequiel09** [comment]
Angular team provides a repo for validating `ngcc` compatibility to make this compatible with Angular v9: https://github.com/angular/ngcc-validation which can aid in fixing this issue when v9 lands.

**Comment by exequiel09** [comment]
This maybe related on how this package is built. I think that we should use https://github.com/ng-packagr/ng-packagr package this repo that conforms to the Angular package format.

**Comment by quedicesebas** [comment]
Now Angular 20...
