### ISSUE TITLE
Module not found: Error: Can't resolve 'ngx-currency' in

### ISSUE THREAD

**Issue by iCodr8** [nbfontana/ngx-currency#65]
I have updated to Angular `8.2.14` and ngx-currency `2.2.0` and I got the following error:

```bash
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ngx-currency' in '/path-to-project'
```

Usage:

```ts
import { NgxCurrencyModule } from 'ngx-currency';

@NgModule({
  imports: [
    ...
    NgxCurrencyModule,
    ...
  ],
})
export class AppModule {
}
```

The module exists in the `node_modules/ngx-currency` directory, but I can't get it working again.

**Any ideas?**

**Comment by nbfontana** [comment]
Hmmm, I just merged some changes and it may have negative impact somehow. If you use the older version it works? I'll check this

**Comment by felippeefreire** [comment]
I get this error on angular build:

> ERROR in : Unexpected value 'NgxCurrencyModule in /opt/atlassian/pipelines/agent/build/node_modules/ngx-currency/src/currency-mask.module.d.ts' imported by the module 'RoutesModule in /opt/atlassian/pipelines/agent/build/src/app/routes/routes.module.ts'. Please add a @NgModule annotation.

**Comment by nbfontana** [comment]
**The v2.2.0 release is broken.** 

I'll ask you guys to stick to the older version **v.2.0.2** w/ angular7.

Meanwhile I'll rewrite the build system using ng-packagr, test it and make a new breaking changes version.

Ok?

**Comment by exequiel09** [comment]
@nbfontana I think the NPM script `copyfiles` is the culprit here. it overrides the `package.json` generated by `ng-packagr`

**Comment by t2developer** [comment]
broke for me too, I went back to the last version (1.5.2). I'm running angular 8.2.11

Let me know when you release a fix.

**Comment by amirdt22** [comment]
2.0.2 worked for me on angular 8

**Comment by Blunderchips** [comment]
Getting the same issue.

**Comment by lomberas** [comment]
Same issue here. Reverting back to [v1.5.2](https://github.com/nbfontana/ngx-currency/releases/tag/v1.5.2) compiled successfully.

**Comment by Alekzv9** [comment]
Same issue, as @t2developer suggested I've to use that version and angular 8.2.14.

**Comment by nbfontana** [comment]
Fixed with a new version: **ngx-currency-v2.2.1** :rocket: 

Tested with the following setup:

```json
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "core-js": "^2.5.4",
    "ngx-currency": "^2.2.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
```

Thanks @exequiel09 for pointing the error in the release script in v2.2.0.

:warning: **LET ME KNOW IF ANYTHING STILL BROKEN** :warning:

Also, if any of you guys want to improve or make some cool changes to *ngx-currency*, just let me know.

I've been away from Angular for a while...

Thank you all.

**Comment by Blunderchips** [comment]
The issue seems to be been resolved

**Comment by iCodr8** [comment]
Works fine, thank you!

**Comment by timhilehin1** [comment]
I am on Angular 17 and using ngx-currency v2.5.3.
I keep getting the error "Module '"ngx-currency"' has no exported member 'NgxCurrencyModule'"

**Comment by ArtemDintecom** [comment]
@timhilehin1 I think on Angular 17 you should use the corresponding version of ngx-currency [17.0.0](https://www.npmjs.com/package/ngx-currency/v/17.0.0).
As of ngx-currency 4.0.0 NgxCurrencyModule no longer exists, you can import the NgxCurrencyDirective directly.
Here's the full [list of changes](https://github.com/nbfontana/ngx-currency/releases/tag/v4.0.0).
More detailed information on how to override settings globally can be found in the [Readme](https://github.com/nbfontana/ngx-currency/tree/v17.0.0?tab=readme-ov-file#getting-started).

**Comment by timhilehin1** [comment]
**Thank you!**
