### ISSUE TITLE
Press and hold delete button does not clear the input

### ISSUE THREAD

**Issue by dvenkatsagar** [nbfontana/ngx-currency#75]
As the title says, I cannot remove the entire value when I press and hold the delete button on the keyboard

For example, lets say I have value of 0.11 in the text box. I place the cursor at the beginning of the value(left most side) and then press and hold delete. 

Expected Result: The text should be cleared.
Actual Result: The text stays as 0.01 with the cursor right after the decimal.
 
Please find the reproducible code sample here: https://stackblitz.com/edit/ngx-currency-delete-issue

**Comment by dvenkatsagar** [comment]
Ok, I managed to fix this issue. I've set up a pull request for this.

**Comment by nbfontana** [comment]
Great work man! I'll make a new release.
