### ISSUE TITLE
Typing decimal or thousands separator should advance cursor

### ISSUE THREAD

**Issue by jlabanca** [nbfontana/ngx-currency#79]
If the cursor is just before the decimal or thousands separator, then typing the decimal or thousands separator should advance the cursor past it. For example, if the value is "$1,234.56" and the cursor just just after the 4, then typing "." should advance the cursor past the decimal.

See PR #78

**Comment by nbfontana** [comment]
Sorry about the late feedback about your work @jlabanca, got busy with work stuff. 

Thank you for your PR. :tada: 

This behavior is now fixed and I also merged your work with the FINANCIAL options.

I'll release a new Version soon.

**Comment by jlabanca** [comment]
Thanks for the review!

**Comment by fergardi** [comment]
Hi, can you help me with https://github.com/nbfontana/ngx-currency/issues/133?
