### ISSUE TITLE
Test with Angular 5

### ISSUE THREAD

**Issue by filosofisto** [nbfontana/ngx-currency#8]
I'm using this component with a Angular 5.2.0 project, and it's working fine.
My suggestion is to confirm that component works fine with Angular 5.x and maybe test with Angular 6.
Confirming these expectation, it will be nice to remove reference that works with Angular >= 2 and < 5.

Att,
Eduardo Ribeiro da Silva

**Comment by nbfontana** [comment]
Hi @filosofisto, I've just tested ngx-currency with Angular 6.0.3 and it seems to work just fine!

I'll remove the reference soon 

:shipit:
