### ISSUE TITLE
[BUG] Able to drag and drop selected text after the decimal

### ISSUE THREAD

**Issue by dvenkatsagar** [nbfontana/ngx-currency#82]
I am able to select a portion of the amount value and then drag and drop it past the decimal point. And it only has a precision config as 2.

Example:
Lets say the value in the textbox displays as '123.456,78' (according to the demo) and I select '456'. Now I click and drag this partial selection past the decimal point at the very end of the value.

Expected Result: It should not do anything ideally, the value should remain as '123.456,78'.
Actual Result: The value becomes '123,.78456'.

Even though the model value doesnt change, the view value gets messed up.

You can reproduce this on the demo site as well: https://nbfontana.github.io/ngx-currency/

**Comment by dvenkatsagar** [comment]
@nbfontana 

I can work on this, but I do need some guidance on whether you want to allow the user to even drag the text like this. If it is allowed, I think a config option would need to be added which the user can use to make the textbox's drag event trigger-able or not, else we can simply ignore the drag event on the textbox.

Ideally, I would prefer the latter option(ignoring the drag event) because that is the easy fix. :p

let me know what you think.

**Comment by dvenkatsagar** [comment]
Ok, I choose the latter option to ignore the drag/drop events for now and fixed it. Its better to have a feature request for the first option. I've kept a pull request along with few other fixes.

**Comment by nbfontana** [comment]
Hello @dvenkatsagar, first of all, great work man!

I really appreciate the effort you put on this PR and I will release a new version with those modifications.

**Comment by nbfontana** [comment]
Available at version `v2.2.4`

**Comment by dvenkatsagar** [comment]
Thank you @nbfontana.
