### ISSUE TITLE
Travis Build error npm for version 2.3.0

### ISSUE THREAD

**Issue by dvenkatsagar** [nbfontana/ngx-currency#84]
npm build is failing and I think the issue with the static variables declared in the input.service.ts in the code.

One easy fix is to include the following code in the file like this:

```
// @dynamic
export class InputService {
...
}
```

I dont know if there is a proper way to fix this.

**Comment by nbfontana** [comment]
Yeah, just saw this after the release. My bad.

I fixed by removing the static operator and using those variables privately with the `this` operator and I already fixed it in `v2.3.1`.

**Comment by dvenkatsagar** [comment]
Thank you @nbfontana
