### ISSUE TITLE
"export 'CurrencyMaskInputMode' was not found in 'ngx-currency'

### ISSUE THREAD

**Issue by randjelovicaleksandar** [nbfontana/ngx-currency#86]
Hello, I am trying to use your library, but I am getting this error: ""export 'CurrencyMaskInputMode' was not found in 'ngx-currency'". I took a look at your code and everything seemed fine. Do you maybe know what could be a problem? Or can you manage to reproduce this bug?

**Comment by dvenkatsagar** [comment]
Quick fix is to not use the CurrencyMaskInputMode and simply put the value for inputMode as 0 or 1.
I do agree the documentation or functionality would need to be updated for this. I can work on this.

**Comment by nbfontana** [comment]
@dvenkatsagar It would be awesome!

**Comment by randjelovicaleksandar** [comment]
Awesome! Thank you!
