### ISSUE TITLE
any possibility to enter negative (-) mark in the input

### ISSUE THREAD

**Issue by slcoder** [nbfontana/ngx-currency#97]
Hi

First of all, thank you very much for this module, it really helped for me.

I'm having an issue of users always attempting to enter (-) mark when they want to add negative value to input, unfortunately, now users have to add numbers and enter (-) mark towards the end, which is not practical.

Any suggestion or help to sort this out?

Thanks

**Comment by slcoder** [comment]
Hi @nbfontana 

Thank you for a prompt response.

**Yes, I think your first approach would be handy.**
b.t.w have you tried like below code,  when the 'allowNegative:true', sometime like , 
`if (this.options.allowNegative && this.rawValue.charAt(0) != "-") 
{ 
	this.rawValue = "-"; 
} `

--my html----
I have configured my input as :
 <input matInput [(ngModel)]="element.amount" currencyMask  
              [options]="{ allowNegative: true }">

now users able to add minus value into the textbox - this is great

my actual issue is: the user does not allow to enter minus mark at the start of the textbox and enter the value, it only allows enter some value and enter a minus mark, that's is kind of odd practice I believe.

Really appreciate your help on this.

Thanks

**Comment by sheta-exin** [comment]
I've tried this function and it seems works

```
changeToNegative() {
        if (this.options.allowNegative && this.rawValue != " " && this.rawValue.charAt(0) != "-" && this.value != 0) {
            // Apply the mask to ensure the min and max values are enforced.
            if (this.rawValue == "" ||this.rawValue == "-"){
                this.rawValue ="-"
            }else{
                this.rawValue = this.applyMask(false, "-" + this.rawValue);

            }
        }
    }
```

**Comment by udamken** [comment]
Any news regarding integration of this fix?

In Germany it's typical to type the minus sign at first - so it would be of great help to have this fix or a bybass.

Besides this I'm very happy with ngx-currency because it works perfect for me.

**Comment by veraw** [comment]
Any update on this, as I also have different geo graphical users requiring the need to enter "-" first before the numeric value?

**Comment by ozgeengin** [comment]
Any fix to this in the near future?

**Comment by antonioclaudioneiva** [comment]
Any fix to this in the near future?

**Comment by Sebas15897** [comment]
¿Alguna solución encontrada, tengo el mismo problema?

**Comment by ElChouaib** [comment]
> I've tried this function and it seems works
> 
> ```
> changeToNegative() {
>         if (this.options.allowNegative && this.rawValue != " " && this.rawValue.charAt(0) != "-" && this.value != 0) {
>             // Apply the mask to ensure the min and max values are enforced.
>             if (this.rawValue == "" ||this.rawValue == "-"){
>                 this.rawValue ="-"
>             }else{
>                 this.rawValue = this.applyMask(false, "-" + this.rawValue);
> 
>             }
>         }
>     }
> ```

where to put this function, please?

**Comment by shenHui-Cheng** [comment]
**Have any news about where to put this function ?**

changeToNegative() {
        if (this.options.allowNegative && this.rawValue != " " && this.rawValue.charAt(0) != "-" && this.value != 0) {
            // Apply the mask to ensure the min and max values are enforced.
            if (this.rawValue == "" ||this.rawValue == "-"){
                this.rawValue ="-"
            }else{
                this.rawValue = this.applyMask(false, "-" + this.rawValue);

            }
        }
    }

**Comment by IvanHrushevich** [comment]
hello! any updates on this?

**Comment by DywiTom** [comment]
bump

**Comment by ArturQuirino** [comment]
Hi! Any updates? I also need that.

**Comment by nbfontana** [comment]
Partially solved by https://github.com/nbfontana/ngx-currency/pull/99

Will prob generate side-effects. It works like a charm with the default `FINANCIAL` input mode, but we prob see more bugs with the other type
